name: Sync README from my-app

on:
  push:
    paths:
      - 'my-app/README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy README
        run: |
          cp my-app/README.md README.md

      - name: Commit and push changes
        run: |
          git config user.name "01-123140180-MegaZayyani"
          git config user.email "mega.123140180@student.itera.ac.id"
          git add README.md
          git commit -m "Sync README from my-app" || echo "No changes to commit"
          git push
